import fs from "fs/promises"
import { existsSync } from "fs"
import type { ParsedSnapRaidConfig } from "@snapraid-webui/shared"

/**
 * Parse snapraid.conf content (string) into a structured object.
 * Extracted for testability without filesystem.
 */
export function parseConfigFromContent(content: string): ParsedSnapRaidConfig {
  const config: ParsedSnapRaidConfig = {
    parity: [],
    content: [],
    data: {},
    exclude: [],
    include: [],
  }

  const lines = content.split("\n")

  for (const line of lines) {
    const trimmed = line.trim()

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith("#")) {
      continue
    }

    // Parse key-value pairs
    const match = trimmed.match(/^(\S+)\s+(.+)$/)
    if (!match) continue

    const [, key, value] = match

    switch (key) {
      case "parity":
        config.parity.push(value)
        break
      case "2-parity":
        config["2-parity"] = config["2-parity"] || []
        config["2-parity"].push(value)
        break
      case "3-parity":
        config["3-parity"] = config["3-parity"] || []
        config["3-parity"].push(value)
        break
      case "4-parity":
        config["4-parity"] = config["4-parity"] || []
        config["4-parity"].push(value)
        break
      case "5-parity":
        config["5-parity"] = config["5-parity"] || []
        config["5-parity"].push(value)
        break
      case "6-parity":
        config["6-parity"] = config["6-parity"] || []
        config["6-parity"].push(value)
        break
      case "content":
        config.content.push(value)
        break
      case "data": {
        // data diskname /path/to/disk/
        const dataMatch = value.match(/^(\S+)\s+(.+)$/)
        if (dataMatch) {
          config.data[dataMatch[1]] = dataMatch[2]
        }
        break
      }
      case "exclude":
        config.exclude.push(value)
        break
      case "include":
        config.include.push(value)
        break
      case "blocksize":
        config.blocksize = parseInt(value, 10)
        break
      case "hashsize":
        config.hashsize = parseInt(value, 10)
        break
      case "autosave":
        config.autosave = parseInt(value, 10)
        break
      case "pool":
        config.pool = value
        break
      case "nohidden":
        config.nohidden = true
        break
    }
  }

  return config
}

/**
 * Parse a snapraid.conf file into a structured object
 */
export async function parseSnapRaidConfig(
  configPath: string,
): Promise<ParsedSnapRaidConfig> {
  if (!existsSync(configPath)) {
    return parseConfigFromContent("")
  }

  const content = await fs.readFile(configPath, "utf-8")
  return parseConfigFromContent(content)
}

/**
 * Serialize a ParsedSnapRaidConfig back to snapraid.conf format
 */
export function serializeSnapRaidConfig(config: ParsedSnapRaidConfig): string {
  const lines: string[] = []

  // Add header comment
  lines.push("# SnapRAID configuration file")
  lines.push("# Generated by SnapRAID Web UI")
  lines.push("")

  // Parity disks
  if (config.parity.length > 0) {
    lines.push("# Parity files")
    for (const parity of config.parity) {
      lines.push(`parity ${parity}`)
    }
    lines.push("")
  }

  // Additional parity levels
  const parityLevels = [
    "2-parity",
    "3-parity",
    "4-parity",
    "5-parity",
    "6-parity",
  ] as const
  for (const level of parityLevels) {
    const parityFiles = config[level]
    if (parityFiles && parityFiles.length > 0) {
      for (const parity of parityFiles) {
        lines.push(`${level} ${parity}`)
      }
    }
  }

  // Content files
  if (config.content.length > 0) {
    lines.push("# Content files")
    for (const content of config.content) {
      lines.push(`content ${content}`)
    }
    lines.push("")
  }

  // Data disks
  const dataEntries = Object.entries(config.data)
  if (dataEntries.length > 0) {
    lines.push("# Data disks")
    for (const [name, path] of dataEntries) {
      lines.push(`data ${name} ${path}`)
    }
    lines.push("")
  }

  // Options
  if (config.blocksize) {
    lines.push(`blocksize ${config.blocksize}`)
  }
  if (config.hashsize) {
    lines.push(`hashsize ${config.hashsize}`)
  }
  if (config.autosave) {
    lines.push(`autosave ${config.autosave}`)
  }
  if (config.pool) {
    lines.push(`pool ${config.pool}`)
  }
  if (config.nohidden) {
    lines.push("nohidden")
  }

  // Excludes
  if (config.exclude.length > 0) {
    lines.push("")
    lines.push("# Exclude patterns")
    for (const exclude of config.exclude) {
      lines.push(`exclude ${exclude}`)
    }
  }

  // Includes
  if (config.include.length > 0) {
    lines.push("")
    lines.push("# Include patterns")
    for (const include of config.include) {
      lines.push(`include ${include}`)
    }
  }

  return lines.join("\n") + "\n"
}

/**
 * Validate a SnapRAID configuration
 */
export function validateSnapRaidConfig(config: ParsedSnapRaidConfig): {
  valid: boolean
  errors: string[]
} {
  const errors: string[] = []

  // Must have at least one parity file
  if (config.parity.length === 0) {
    errors.push("At least one parity file must be defined")
  }

  // Must have at least one content file
  if (config.content.length === 0) {
    errors.push("At least one content file must be defined")
  }

  // Must have at least one data disk
  if (Object.keys(config.data).length === 0) {
    errors.push("At least one data disk must be defined")
  }

  // Content files should be stored in multiple locations
  if (config.content.length < 2) {
    errors.push(
      "Warning: It is recommended to have multiple content files for redundancy",
    )
  }

  return {
    valid: errors.filter((e) => !e.startsWith("Warning")).length === 0,
    errors,
  }
}
